name: Playwright Tests

on:
  push:
    branches:
      - main
      - primeirabranch  # ajuste conforme suas necessidades

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with xvfb
        run: xvfb-run npm test
