jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: xvfb-run npm test
